--- #YAML:1.0
name:               Bot-BasicBot-Pluggable-Module-TwitterWatch
version:            0.01
abstract:           report new tweets matching given search patterns
author:
    - David Precious <davidp@preshweb.co.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bot::BasicBot::Pluggable::Module:  0
    HTML::Entities:       0
    Net::Twitter::Lite:   0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
